[package]
name = "table"
version = "0.1.0"
authors = ["katand <katandps@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
model = {path = "../model"}

# JSONのパース
serde = {version = "1.0", features= ["derive"]}
serde_json = "1.0"
envy = "0.4.2"
lazy_static = "1.4.0"

#urlパーサ
url = "2.1.1"

#エラー処理
anyhow = "1.0"

#HTMLパーサ
scraper = "0.11.0"

# HTTPリクエスト/非同期処理
reqwest = {version = "0.10.4", features = ["json"]}
tokio = { version = "0.2", features = ["macros"]}
