[package]
name = "table"
version = "0.1.0"
authors = ["katand <katandps@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
model = {path = "../model"}
log = "0.4.17"

# JSONのパース
serde = {version = "1.0.137", features= ["derive"]}
serde_json = "1.0.81"
envy = "0.4.2"
lazy_static = "1.4.0"

#urlパーサ
url = "2.1.1"

#エラー処理
anyhow = "1.0"
thiserror = "1.0.23"

#HTMLパーサ
scraper = "0.13.0"
cssparser = "0.29.3"
selectors = "0.23.0"

# HTTPリクエスト/非同期処理
reqwest = {version = "0.11.4", features = ["json"]}
tokio = { version = "1", features = ["macros"]}
futures = "0.3.15"
