table! {
    score (sha256) {
        sha256 -> Text,
        mode -> Integer,
        clear -> Integer,
        epg -> Integer,
        lpg -> Integer,
        egr -> Integer,
        lgr -> Integer,
        egd -> Integer,
        lgd -> Integer,
        ebd -> Integer,
        lbd -> Integer,
        epr -> Integer,
        lpr -> Integer,
        ems -> Integer,
        lms -> Integer,
        notes -> Integer,
        combo -> Integer,
        minbp -> Integer,
        playcount -> Integer,
        clearcount -> Integer,
        //history -> Integer, nullが入っていたりする
        scorehash -> Text,
        option -> Integer,
        random -> Integer,
        date -> Integer,
        state -> Integer,
        //trophy -> Text,
        //ghost -> Text,
    }
}

#[derive(Queryable)]
pub struct Score {
    pub sha256: String,
    pub mode: i32,
    pub clear: i32,
    pub epg: i32,
    pub lpg: i32,
    pub egr: i32,
    pub lgr: i32,
    pub egd: i32,
    pub lgd: i32,
    pub ebd: i32,
    pub lbd: i32,
    pub epr: i32,
    pub lpr: i32,
    pub ems: i32,
    pub lms: i32,
    pub notes: i32,
    pub combo: i32,
    pub minbp: i32,
    pub playcount: i32,
    pub clearcount: i32,
    //pub history: i32,
    pub scorehash: String,
    pub option: i32,
    pub random: i32,
    pub date: i32,
    pub state: i32,
    //pub trophy: String,
    //pub ghost: String,
}
