[package]
name = "mysql"
version = "0.1.0"
authors = ["katand <katandps@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
diesel = { version = "1.4.5", features = ["mysql", "chrono"] }
diesel_codegen = "0.16.1"
serde = {version = "1.0", features= ["derive"]}
chrono = "*"

model = { path = "../model" }

#エラー処理
anyhow = "1.0"

envy = "0.4.2"
lazy_static = "1.4.0"
