version: 0.2

env:
  secrets-manager:
    DOCKERHUB_USER: arn:aws:secretsmanager:ap-northeast-1:847110695266:secret:DockerHub-SaAUAX:username
    DOCKERHUB_PASS: arn:aws:secretsmanager:ap-northeast-1:847110695266:secret:DockerHub-SaAUAX:password
  variables:
    DOCKER_BUILDKIT: "1"

phases:
  pre_build:
    commands:
      - echo Logging in to Docker Hub...
      - echo $DOCKERHUB_PASS | docker login -u $DOCKERHUB_USER --password-stdin
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
  build:
    commands:
      - echo "docker build ./ -t $TARGET_IMAGE_NAME:$CODEBUILD_RESOLVED_SOURCE_VERSION"
      - docker build ./ -t $TARGET_IMAGE_NAME:$CODEBUILD_RESOLVED_SOURCE_VERSION
      - docker build ./ -t $TARGET_IMAGE_NAME:latest
  post_build:
    commands:
      - docker push $TARGET_IMAGE_NAME:$CODEBUILD_RESOLVED_SOURCE_VERSION
      - docker push $TARGET_IMAGE_NAME:latest