[package]
name = "beatoraja_play_recommend"
version = "0.1.0"
authors = ["katand <katandps@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
diesel = { version = "0.15.0", features = ["sqlite"]}
diesel_codegen = {version = "0.15.0", features = ["sqlite"]}
dotenv = "0.10.1"