[package]
name = "beatoraja_play_recommend"
version = "0.1.0"
authors = ["katand <katandps@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]

members = [
    "crates/model",
    "crates/ui",
    "crates/send_slack",
    "crates/config"
]

[dependencies]
"model" = {path = "crates/model"}
"ui" = {path = "crates/ui"}
"send_slack" = {path = "crates/send_slack"}
"config" = {path = "crates/config"}