[workspace]
members = [
    "crates/model",
    "crates/send_slack",
    "crates/table",
    "crates/sqlite",
    "crates/mysql",
    "crates/server",
    "crates/oauth_google",
    "crates/repository",
    "crates/session",
]
resolver = "2"
