score_db_url="./files/score.db"
scorelog_db_url="./files/scorelog.db"
songdata_db_url="./files/songdata.db"

mysql_url="mysql://root:root@mysql:3306/user_data"
redis_url="redis://session-redis:6379"
client_url="http://localhost:8080"
client_domain="localhost"

#output_type="SLACK"|"STDOUT"|"JSON"|"TEXT"
output_type="TEXT"

table_urls=[
    "http://www.ribbit.xyz/bms/tables/insane.html",
    "http://www.ribbit.xyz/bms/tables/overjoy.html",
    "https://stellabms.xyz/st/table.html",
    "https://stellabms.xyz/sl/table.html",
    "http://flowermaster.web.fc2.com/lrnanido/gla/LN.html",
    "http://rattoto10.jounin.jp/table_insane.html",
    "http://rattoto10.jounin.jp/table.html",
    "http://walkure.net/hakkyou/for_glassist/bms/?lamp=easy"
]
table_index=1

#timestamp=1546268400
local_cache_url="./files/cache.json"
coloring_table=false


google_oauth_client_id="Set Environment Variables"
google_oauth_client_secret="Set Environment Variables"
google_oauth_redirect_uri="https://localhost:4431/oauth"
