services:
  app:
    build: ./docker/builder/
    container_name: app
    ports:
      - "8000:8000"
      - "4431:4431"
    volumes:
      # - ~/.aws/:/root/.aws/ro
      - ./:/app
    environment:
      - CARGO_BUILD_TARGET_DIR=/tmp/target
    env_file:
      - .env
    restart: always
    depends_on:
      - mysql
    # #開発時はコメントアウト
    # logging:
    #   driver: awslogs
    #   options:
    #     awslogs-region: ap-northeast-1
    #     awslogs-group: dev-beatoraja-play-recommend-log
    #     awslogs-stream: app

  mysql:
    image: mysql:8.4
    container_name: mysql
    restart: always
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    volumes:
      - ./db/data:/var/lib/mysql
      - ./db/my.cnf:/etc/mysql/conf.d/my.cnf:ro
      #- ./db/sql:/docker-entrypoint-initdb.d:ro
      #- /etc/group:/etc/group:ro
      #- /etc/passwd:/etc/passwd:ro
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: user_data
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
