[[tables]]
url = "https://darksabun.github.io/table/archive/normal1/"
id = 1
title = "通常BMS難易度表"

[[tables]]
url = "https://darksabun.github.io/table/archive/insane1/"
id = 2
title = "発狂BMS難易度表"

[[tables]]
url = "https://stellabms.xyz/sl/table.html"
id = 3
title = "Satellite難易度表"
