[package]
name = "send_slack"
version = "0.1.0"
authors = ["katand <katandps@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# HTTPリクエスト/非同期処理
reqwest = {version = "0.10.4", features = ["json", "blocking"]}
tokio = { version = "1", features = ["macros"]}

# JSONのパース
serde = {version = "1.0", features= ["derive"]}
serde_json = "1.0"
lazy_static = "1.4.0"
envy = "0.4.2"

#エラー処理
anyhow = "1.0"