[package]
name = "model"
version = "0.1.0"
authors = ["katand <katandps@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# 環境変数
dotenv = "0.10"

# SqLiteへのアクセス
diesel = { version = "1.4.4", features = ["sqlite"]}
diesel_codegen = "0.16.1"

# JSONのパース
serde = {version = "1.0", features= ["derive"]}
serde_json = "1.0"

# 日時を扱う
chrono = "0.4.11"

# HTTPリクエスト/非同期処理
reqwest = {version = "0.10.4", features = ["json"]}
tokio = { version = "0.2", features = ["macros"]}

#HTMLパーサ
scraper = "0.11.0"

#urlパーサ
url = "2.1.1"

#エラー処理
anyhow = "1.0"

config = {path = "../config"}
send_slack = {path="../send_slack"}