[package]
name = "server"
version = "0.1.0"
authors = ["katand <katandps@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures = "0.3.8"

tokio = { version = "1", features = ["full"] }
warp = { version = "0.3.1", features = ["tls", "compression"] }
reqwest = { version = "0.11.4", features = ["json"] }

dotenv = "0.10"
env_logger = "0.7.1"
log = "0.4.16"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

tempfile = "3.2.0"

r2d2 = "0.8.9"
bytes = "1"
http = "0.2.2"

rand = "0.8.0"
rand_chacha = "0.3.0"
bigint = "4.4.3"
base64 = "0.13.0"

diesel = { version = "1.4.5", features = ["mysql", "r2d2"] }
chrono = "0.4.19"
redis = "0.19.0"

anyhow = "1.0.36"
thiserror = "1.0.23"
lazy_static = "1.4.0"
envy = "0.4.2"

model = { path = "../model" }
table = { path = "../table" }
sqlite = { path = "../sqlite" }
mysql = { path = "../mysql" }
oauth_google = { path = "../oauth_google" }
repository = { path = "../repository" }