[package]
name = "server"
version = "0.1.0"
authors = ["katand <katandps@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures = "0.3.21"

tokio = { version = "1.18.1", features = ["full"] }
warp = { version = "0.3.3", features = ["tls", "compression"] }
reqwest = { version = "0.11.20", features = ["json"] }

env_logger = "0.9.0"
log = "0.4.17"

serde = {version = "1.0.137", features= ["derive"]}
serde_json = "1.0.81"

tempfile = "3.2.0"

r2d2 = "0.8.9"
bytes = "1.1.0"
http = "0.2.2"

rand = "0.8.0"
rand_chacha = "0.3.0"
base64 = "0.13.0"

diesel = { version = "2.0.2", features = ["mysql", "r2d2"] }
chrono = "0.4.19"
redis = "0.21.5"

anyhow = "1.0.75"
thiserror = "1.0.31"
lazy_static = "1.4.0"
envy = "0.4.2"

model = { path = "../model" }
table = { path = "../table" }
sqlite = { path = "../sqlite" }
mysql = { path = "../mysql" }
oauth_google = { path = "../oauth_google" }
repository = { path = "../repository" }